# Generated by Django 4.2.10 on 2024-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=226, verbose_name='Название')),
                ('trailer', models.CharField(max_length=500, verbose_name='Ссылка на трейлер из youtube')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limit', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('season', models.PositiveIntegerField(verbose_name='Сезон')),
                ('num_serials', models.PositiveIntegerField(verbose_name='Кол-во серий')),
                ('release_date', models.DateField(verbose_name='Дата выхода сериала')),
                ('actors', models.ManyToManyField(to='films.actormodel', verbose_name='Актеры')),
                ('country', models.ManyToManyField(to='films.countrymodel', verbose_name='Страны')),
                ('genre', models.ManyToManyField(to='films.genremodel', verbose_name='Жанры')),
                ('producer', models.ManyToManyField(to='films.producermodel', verbose_name='Режиссер')),
                ('reaction', models.ManyToManyField(blank=True, to='films.reactionmodel', verbose_name='Лайк/Дизлайк')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
    ]
