# Generated by Django 4.2.10 on 2024-05-14 10:24

from django.db import migrations, models
import django.db.models.deletion
import some_proj.media_for_kino_card.utils.shared_files.clean_poster
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=226, verbose_name='Название')),
                ('poster', sorl.thumbnail.fields.ImageField(blank=True, upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, validators=[some_proj.media_for_kino_card.utils.shared_files.clean_poster.poster_validator], verbose_name='Постер')),
                ('trailer', models.CharField(max_length=500, verbose_name='Ссылка на трейлер из youtube')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limit', models.PositiveSmallIntegerField(verbose_name='Возрастное ограничение')),
                ('season', models.PositiveSmallIntegerField(verbose_name='Сезон')),
                ('num_serials', models.PositiveSmallIntegerField(verbose_name='Кол-во серий')),
                ('release_date', models.DateField(verbose_name='Дата выхода сериала')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность серии')),
                ('actors', models.ManyToManyField(to='films.actormodel', verbose_name='Актеры')),
                ('country', models.ManyToManyField(to='films.countrymodel', verbose_name='Страны')),
                ('genre', models.ManyToManyField(to='films.genremodel', verbose_name='Жанры')),
                ('producers', models.ManyToManyField(to='films.producermodel', verbose_name='Режиссер')),
                ('reaction', models.ManyToManyField(blank=True, to='films.reactionmodel', verbose_name='Лайк/Дизлайк')),
            ],
            options={
                'verbose_name': 'сериал',
                'verbose_name_plural': 'сериалы',
            },
        ),
        migrations.CreateModel(
            name='PhotoSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_serial', models.ImageField(upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Кадр из сериала')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadrs', to='serials.serialmodel', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'кадр из сериала',
                'verbose_name_plural': 'кадры из сериалов',
            },
        ),
    ]
