# Generated by Django 4.2.10 on 2024-03-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoserial',
            options={'verbose_name': 'кадр из сериала', 'verbose_name_plural': 'кадры из сериалов'},
        ),
        migrations.AlterField(
            model_name='photoserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadrs', to='serials.serialmodel', verbose_name='Сериал'),
        ),
        migrations.AlterField(
            model_name='serialmodel',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность серии'),
        ),
    ]
