# Generated by Django 4.2.10 on 2024-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialmodel',
            name='poster',
            field=models.FileField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
