# Generated by Django 4.2.10 on 2024-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_photoserial_options_alter_photoserial_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoserial',
            name='photo_serial',
            field=models.ImageField(upload_to='photos_serials/', verbose_name='Кадр из сериала'),
        ),
        migrations.AlterField(
            model_name='serialmodel',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
