# Generated by Django 4.2.10 on 2024-03-20 19:00

from django.db import migrations, models
import some_proj.films.models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_alter_serialmodel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialmodel',
            name='poster',
            field=models.ImageField(blank=True, upload_to=some_proj.films.models.generate_filename_photos, verbose_name='Постер'),
        ),
    ]
