# Generated by Django 4.2.10 on 2024-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_alter_serialmodel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialmodel',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/<function generate_filename at 0x1080528c0>', verbose_name='Постер'),
        ),
    ]
