# Generated by Django 4.2.10 on 2024-03-20 21:19

from django.db import migrations, models
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0008_alter_serialmodel_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoserial',
            name='photo_serial',
            field=models.ImageField(upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Кадр из сериала'),
        ),
    ]
