# Generated by Django 4.2.10 on 2024-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0009_alter_photoserial_photo_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialmodel',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Длительность серии'),
        ),
        migrations.AlterField(
            model_name='serialmodel',
            name='num_serials',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во серий'),
        ),
        migrations.AlterField(
            model_name='serialmodel',
            name='season',
            field=models.PositiveSmallIntegerField(verbose_name='Сезон'),
        ),
    ]
