image: docker:20.10.16
stages:
  - lint
  - tests

variables:
  POSTGRES_USER: 'some_proj'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_some_proj'
  POSTGRES_HOST_AUTH_METHOD: trust
  CELERY_BROKER_URL: 'redis://redis:6379/0'

precommit:
  stage: lint
  image: python:3.10
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

pytest:
  stage: tests
  resource_group: test_group
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm django python manage.py makemigrations
    - docker-compose -f local.yml run --rm django python manage.py migrate
    - docker-compose -f local.yml run --rm django python manage.py collectstatic --noinput
    - docker-compose -f local.yml up -d
    - docker ps
  script:
    - docker-compose -f local.yml run django pytest
