# Generated by Django 4.2.10 on 2024-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Продюсер',
                'verbose_name_plural': 'Продюсеры',
            },
        ),
        migrations.CreateModel(
            name='ReactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.BooleanField(verbose_name='Лайк/Дизлайк')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
            },
        ),
        migrations.CreateModel(
            name='SerialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=226, verbose_name='Название')),
                ('trailer', models.CharField(max_length=500, verbose_name='Ссылка на трейлер из youtube')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limit', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('num_seasons', models.PositiveIntegerField(verbose_name='Кол-во сезонов')),
                ('num_serials', models.PositiveIntegerField(verbose_name='Кол-во серий')),
                ('country', models.ManyToManyField(to='films.countrymodel', verbose_name='Страны')),
                ('genre', models.ManyToManyField(to='films.genremodel', verbose_name='Жанры')),
                ('producer', models.ManyToManyField(to='films.producermodel', verbose_name='Режиссер')),
                ('reaction', models.ManyToManyField(blank=True, to='films.reactionmodel', verbose_name='Лайк/Дизлайк')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=226, verbose_name='Название')),
                ('trailer', models.CharField(max_length=500, verbose_name='Ссылка на трейлер из youtube')),
                ('description', models.TextField(verbose_name='Описание')),
                ('age_limit', models.IntegerField(verbose_name='Возрастное ограничение')),
                ('release_date', models.DateField(verbose_name='Дата выхода фильма')),
                ('country', models.ManyToManyField(to='films.countrymodel', verbose_name='Страны')),
                ('genre', models.ManyToManyField(to='films.genremodel', verbose_name='Жанры')),
                ('producer', models.ManyToManyField(to='films.producermodel', verbose_name='Режиссер')),
                ('reaction', models.ManyToManyField(blank=True, to='films.reactionmodel', verbose_name='Лайк/Дизлайк')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
