# Generated by Django 4.2.10 on 2024-04-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_for_kino_card', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seelatecontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='reactionmodel',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reactionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='producermodel',
            name='films_made',
            field=models.ManyToManyField(blank=True, to='films.filmmodel', verbose_name='Фильмы/сериалы'),
        ),
        migrations.AddField(
            model_name='photofilm',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadrs', to='films.filmmodel', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='iscontentwatch',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='iscontentwatch',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_for_kino_card.mediafile', verbose_name='Медиа'),
        ),
        migrations.AddField(
            model_name='iscontentwatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='actors',
            field=models.ManyToManyField(to='films.actormodel', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='country',
            field=models.ManyToManyField(to='films.countrymodel', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='genre',
            field=models.ManyToManyField(to='films.genremodel', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='producers',
            field=models.ManyToManyField(to='films.producermodel', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='reaction',
            field=models.ManyToManyField(blank=True, to='films.reactionmodel', verbose_name='Лайк/Дизлайк'),
        ),
        migrations.AddField(
            model_name='favoritecontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='favoritecontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='actormodel',
            name='films_participated',
            field=models.ManyToManyField(blank=True, to='films.filmmodel', verbose_name='Участие актера в следующих фильмах'),
        ),
    ]
