# Generated by Django 4.2.10 on 2024-02-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='actors',
            field=models.ManyToManyField(to='films.actormodel', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='serialmodel',
            name='actors',
            field=models.ManyToManyField(to='films.actormodel', verbose_name='Актеры'),
        ),
    ]
