# Generated by Django 4.2.10 on 2024-10-09 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genremodel',
            name='data_added',
            field=models.DateField(default=datetime.date(2023, 1, 1), verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
