# Generated by Django 4.2.10 on 2024-05-05 14:16

from django.db import migrations
import some_proj.media_for_kino_card.utils.shared_files.clean_poster
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='', validators=[some_proj.media_for_kino_card.utils.shared_files.clean_poster.clean], verbose_name='Постер'),
        ),
    ]
