# Generated by Django 4.2.10 on 2024-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actormodel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='persons photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=models.FileField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='persons photos/', verbose_name='Фото'),
        ),
    ]
