# Generated by Django 4.2.10 on 2024-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_genremodel_options_alter_producermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photofilm',
            name='photo_film',
            field=models.ImageField(upload_to='photos_films/', verbose_name='Кадр из фильма'),
        ),
    ]
