# Generated by Django 4.2.10 on 2024-05-05 17:01

from django.db import migrations
import some_proj.media_for_kino_card.utils.shared_files.clean_poster
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_filmmodel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, validators=[some_proj.media_for_kino_card.utils.shared_files.clean_poster.clean], verbose_name='Постер'),
        ),
    ]
