# Generated by Django 4.2.10 on 2024-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_actormodel_photo_alter_filmmodel_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
