# Generated by Django 4.2.10 on 2024-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_photofilm_photo_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
