# Generated by Django 4.2.10 on 2024-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_filmmodel_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='age_limit',
            field=models.PositiveIntegerField(verbose_name='Возрастное ограничение'),
        ),
    ]
