# Generated by Django 4.2.10 on 2024-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_filmmodel_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Длительность фильма'),
        ),
    ]
