# Generated by Django 4.2.10 on 2024-03-20 21:19

from django.db import migrations, models
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_filmmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actormodel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photofilm',
            name='photo_film',
            field=models.ImageField(upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Кадр из фильма'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Фото'),
        ),
    ]
