# Generated by Django 4.2.10 on 2024-03-27 19:11

from django.db import migrations
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_actormodel_photo_alter_photofilm_photo_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='poster',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos, verbose_name='Постер'),
        ),
    ]
