# Generated by Django 4.2.10 on 2024-03-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_for_kino_card', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmediafile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical медия', 'verbose_name_plural': 'historical медии'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'медия', 'verbose_name_plural': 'медии'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'качество', 'verbose_name_plural': 'качества'},
        ),
        migrations.AlterModelOptions(
            name='urlsinmedia',
            options={'verbose_name': 'ссылка на локальный файл/амазон', 'verbose_name_plural': 'ссылки на локальные файлы/амазон'},
        ),
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='urlsinmedia',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_for_kino_card.quality', verbose_name='Качество'),
        ),
        migrations.AlterField(
            model_name='urlsinmedia',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='Ссылка'),
        ),
    ]
