# Generated by Django 4.2.10 on 2024-03-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
