# Generated by Django 4.2.10 on 2024-04-23 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import some_proj.blog.snippets.film_snippet
import some_proj.blog.snippets.serial_snippet
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster
import some_proj.users.managers
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('films', '0002_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('serials', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('body', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'hr', 'blockquote'], help_text='Введите описание', label='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите изображение', icon='image', label='Изображение', template='blocks/imgblock.html', upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos)), ('content', wagtail.embeds.blocks.EmbedBlock(help_text='Пример ссылки: https://www.youtube.com/watch?v=5mM0fX_kKCU', label='Ссылка на видео контент')), ('film', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.film_snippet.FilmBlogModel, help_text='Укажите фильм', label='Фильм', required=False)), ('serial', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.serial_snippet.SerialBlogModel, help_text='Укажите сериал', label='Сериал', required=False)), ('slides', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.serial_snippet.SerialBlogModel, label='Кадры из фильма/сериала', required=False))], blank=True, verbose_name='Место для творчества')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FilmBlogModel',
            fields=[
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('films.filmmodel',),
        ),
        migrations.CreateModel(
            name='FilmsCadrsModel',
            fields=[
            ],
            options={
                'verbose_name': 'кадр из фильма',
                'verbose_name_plural': 'кадры из фильмов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('films.photofilm',),
        ),
        migrations.CreateModel(
            name='SerialBlogModel',
            fields=[
            ],
            options={
                'verbose_name': 'сериал',
                'verbose_name_plural': 'сериалы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serials.serialmodel',),
        ),
        migrations.CreateModel(
            name='SlidesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_photos', models.ManyToManyField(blank=True, to='films.photofilm')),
                ('serial_photos', models.ManyToManyField(blank=True, to='serials.photoserial')),
            ],
            options={
                'verbose_name': 'кадр с фильма/сериала',
                'verbose_name_plural': 'кадры с фильмов/сериалов',
            },
        ),
        migrations.CreateModel(
            name='BlogTagPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tag',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogTagPage', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='BlockImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Текст слайда')),
                ('blog', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='blog.blogpage')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorBlog',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=250, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, verbose_name='Фамилия')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почтв')),
                ('author_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение автора')),
                ('block_post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', some_proj.users.managers.UserManager()),
            ],
        ),
    ]
