# Generated by Django 4.2.10 on 2024-05-14 10:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.models.collections


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('films', '0001_initial'),
        ('serials', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmBlogModel',
            fields=[
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('films.filmmodel',),
        ),
        migrations.CreateModel(
            name='SerialBlogModel',
            fields=[
            ],
            options={
                'verbose_name': 'сериал',
                'verbose_name_plural': 'сериалы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serials.serialmodel',),
        ),
        migrations.AddField(
            model_name='customrendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='blog.customimage'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='collection',
            field=models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
