# Generated by Django 4.2.10 on 2024-04-24 08:16

from django.db import migrations
import some_proj.blog.snippets.film_snippet
import some_proj.blog.snippets.serial_snippet
import some_proj.blog.snippets.slides_snippet
import some_proj.media_for_kino_card.utils.shared_files.generate_name_poster
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'hr', 'blockquote'], help_text='Введите описание', label='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Загрузите изображение', icon='image', label='Изображение', template='blocks/imgblock.html', upload_to=some_proj.media_for_kino_card.utils.shared_files.generate_name_poster.generate_filename_photos)), ('content', wagtail.embeds.blocks.EmbedBlock(help_text='Пример ссылки: https://www.youtube.com/watch?v=5mM0fX_kKCU', label='Ссылка на видео контент')), ('film', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.film_snippet.FilmBlogModel, help_text='Укажите фильм', label='Фильм', required=False)), ('serial', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.serial_snippet.SerialBlogModel, help_text='Укажите сериал', label='Сериал', required=False)), ('slides', wagtail.snippets.blocks.SnippetChooserBlock(some_proj.blog.snippets.slides_snippet.SlidesModel, label='Кадры из фильма/сериала', required=False))], blank=True, verbose_name='Место для творчества'),
        ),
    ]
