# Generated by Django 4.2.10 on 2024-04-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmsCadrsModel',
        ),
    ]
