# Generated by Django 4.2.10 on 2024-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorblog',
            name='profession',
        ),
        migrations.AddField(
            model_name='authorblog',
            name='profession',
            field=models.ManyToManyField(blank=True, help_text='Выберите профессию', to='blog.profession', verbose_name='Профессия'),
        ),
    ]
