# Generated by Django 4.2.10 on 2024-04-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorblog',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'профессия', 'verbose_name_plural': 'профессии'},
        ),
        migrations.RemoveField(
            model_name='authorblog',
            name='profession',
        ),
        migrations.AddField(
            model_name='authorblog',
            name='profession',
            field=models.ForeignKey(blank=True, help_text='Выберите профессию', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.profession', verbose_name='Профессия'),
        ),
    ]
