# Generated by Django 4.2.10 on 2024-04-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_customimage_customrendition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
