# Generated by Django 4.2.10 on 2024-04-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_customimage_customrendition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockSlideImages',
        ),
    ]
