# Generated by Django 4.2.10 on 2024-04-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_blockslideimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadrsModel',
        ),
    ]
