# Generated by Django 4.2.10 on 2024-04-27 08:10

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_cadrsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtagpage',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage'),
        ),
    ]
