# Generated by Django 4.2.10 on 2024-04-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogtagpage_content_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='tag',
            new_name='tags',
        ),
    ]
